### ISSUE TITLE
NoClassDefFoundError Exception

### ISSUE THREAD

**Issue by joker0986** [klinovp/pronto#10]
Hi good evening,
I've a problem, when I run the file "run_example_brc.sh" I get the following error:

**Exception in thread "main" java.lang.NoClassDefFoundError: uk/ac/manchester/cs/graph/Tree
    at com.clarkparsia.pronto.index.RandomConceptTypeSetGenImpl.generateConceptTypes(RandomConceptTypeSetGenImpl.java:81)
    at com.clarkparsia.pronto.index.RandomConceptTypeSetGenImpl.generate(RandomConceptTypeSetGenImpl.java:69)
    at com.clarkparsia.pronto.lp.BasicLPGeneratorImpl.getLPforPSAT(BasicLPGeneratorImpl.java:62)
    at com.clarkparsia.pronto.lp.CGLPGeneratorImpl.getLPforPSAT(CGLPGeneratorImpl.java:89)
    at com.clarkparsia.pronto.lp.CCSetAnalyzerImpl2.getMinimalUnsatSubsets(CCSetAnalyzerImpl2.java:114)
    at com.clarkparsia.pronto.HSOptimizedLexReasoner.computeMinUnsatisfiableSubsets(HSOptimizedLexReasoner.java:115)
    at com.clarkparsia.pronto.ProntoQueryProcessor.process(ProntoQueryProcessor.java:114)
    at com.clarkparsia.pronto.Pronto.run(Pronto.java:129)
    at com.clarkparsia.pronto.Pronto.main(Pronto.java:65)
Caused by: java.lang.ClassNotFoundException: uk.ac.manchester.cs.graph.Tree
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 9 more**

My O.S. is Ubuntu 15.10 x86. 
Can you tell me what's the problem?

Sorry for my english!
Thank you so much for your time.
Best regard

**Comment by joker0986** [comment]
Hi, good morning,
maybe I have the problem that I write above because the file **benchmarksuite.ppq** there is not in a repository and for this cause I have replaced in the script file **run_example_brc.sh** the file **benchmarksuite.ppq** with **query.ppq**. Please can you upload the file **benchmarksuite.ppq**?

Thank you so much for your time.
Best regards.
